// Tüm kullanıcı metinleri (docs/design/driver-mobile-faz2.md Bölüm 7 + onaylı görsel tasarım).
// Sunucunun `error.message` metni kullanıcıya gösterilmez; `error.code` buradaki metinlere eşlenir.

export const T = {
  common: {
    errNetwork: 'İnternet bağlantısı yok. Tekrar deneyin.',
    errServer: 'Sunucuya ulaşılamadı. Biraz sonra tekrar deneyin.',
    retry: 'TEKRAR DENE',
    openSettings: 'AYARLARI AÇ',
    loading: 'Yükleniyor…',
    back: 'Geri',
    updating: 'Güncelleniyor…',
  },
  login: {
    brand: 'DurakNet',
    title: 'Şoför girişi',
    phone: 'Telefon',
    phonePlaceholder: '05XX XXX XX XX',
    password: 'Şifre',
    passwordPlaceholder: 'Şifreniz',
    show: 'Göster',
    hide: 'Gizle',
    submit: 'GİRİŞ YAP',
    submitting: 'Giriş yapılıyor…',
    noAccount: 'Hesabınız yok mu?',
    register: 'KAYIT OL',
    forgot: 'Şifrenizi unuttuysanız durağınıza başvurun.',
    errCredentials: 'Telefon veya şifre hatalı.',
    errSuspended: 'Hesabınız askıya alındı. Durağınızla görüşün.',
    errRateLimited: (wait: string) => `Çok fazla deneme. ${wait} sonra tekrar deneyin.`,
    lockedButton: (clock: string) => `${clock} SONRA DENEYİN`,
    errPhoneFormat: 'Telefon numarasını kontrol edin.',
    errPasswordEmpty: 'Şifrenizi girin.',
  },
  register: {
    title: 'Kayıt ol',
    intro: 'Hesabınız yönetici onayından sonra açılır.',
    fullName: 'Ad soyad',
    phone: 'Telefon',
    password: 'Şifre (en az 8 karakter)',
    plate: 'Plaka',
    platePlaceholder: '34 ABC 123',
    licenseNo: 'Ruhsat no',
    vehicleModel: 'Araç modeli (isteğe bağlı)',
    vehicleColor: 'Araç rengi (isteğe bağlı)',
    submit: 'KAYDI GÖNDER',
    submitting: 'Gönderiliyor…',
    errConflict: 'Bu telefon veya plaka zaten kayıtlı.',
    errFullName: 'Ad soyad en az 2 karakter olmalı.',
    errPassword: 'Şifre en az 8 karakter olmalı.',
    errPlate: 'Plakayı kontrol edin (ör. 34 ABC 123).',
    errLicenseNo: 'Ruhsat numarasını kontrol edin.',
    errTooLong: 'Bu alan çok uzun.',
  },
  pending: {
    title: 'Hesabınız onay bekliyor',
    body: 'Yönetici onayladığında giriş yapabilirsiniz. Onay için durağınızla görüşün.',
    hint: 'Sık denemeyin: çok sayıda deneme girişi 15 dakika kilitler.',
    back: 'GİRİŞE DÖN',
  },
  home: {
    plate: 'PLAKA',
    account: 'Hesap',
    active: 'AKTİFSİNİZ',
    activeSub: 'Çağrı almaya hazırsınız.',
    passive: 'PASİFSİNİZ',
    passiveSub: 'Çağrı almıyorsunuz.',
    goOnline: 'AKTİF OL',
    goOffline: 'PASİF OL',
    gettingFix: 'Konum alınıyor…',
    goingOnline: 'Aktif olunuyor…',
    goingOnlineSub: 'Konumunuz gönderiliyor.',
    goingOffline: 'Pasif olunuyor…',
    goingOfflineSub: 'Konum paylaşımı durduruluyor.',
    connecting: 'Bağlanıyor…',
    connectingSub: 'Durumunuz sunucudan alınıyor.',
    unknown: 'Durum bilinmiyor',
    unknownSub: 'Bağlantı gelince durumunuz kontrol edilecek.',
    busy: 'YOLCULUKTASINIZ',
    busySub: 'Yolculuk sürerken durumunuz değişmez.',
    offlinePendingTitle: 'Pasife geçiliyor',
    offlinePendingSub: 'Bağlantı gelince onaylanacak.',
    offlinePending: 'Pasife geçiliyor. Bağlantı gelince onaylanacak.',
    reactivating: 'Yeniden aktif olunuyor…',
    reactivatingSub: 'Bağlantı koptuğu için pasife düşmüştünüz.',
    errNoConnection: 'Bağlantı yok. Bağlanınca tekrar deneyin.',
    errNoFix: 'Konum alınamadı. Açık alana çıkıp tekrar deneyin.',
    errGoOnlineFailed: 'Aktif olunamadı. Tekrar deneyin.',
    errGoOnlineTimeout: 'Yanıt gelmedi. Durumunuz bağlantı gelince güncellenecek.',
    errOfflineBusy: 'Aktif işiniz varken pasif olamazsınız.',
    errTrackingFailed: 'Konum paylaşımı başlatılamadı. Tekrar deneyin.',
    a11yNowActive: 'Aktif oldunuz. Çağrı alabilirsiniz.',
    a11yNowPassive: 'Pasif oldunuz.',
    buttonA11y: (label: string, title: string) => `${label}. Durum: ${title}`,
    dismissNotice: 'Bildirimi kapat',
  },
  chip: {
    connected: 'Bağlı',
    connecting: 'Bağlanıyor…',
    disconnected: 'Bağlantı yok',
    locGood: 'Konum iyi',
    locPoor: (m: number) => `Konum zayıf (±${m} m)`,
    locNone: 'Konum yok',
    gpsOff: 'GPS kapalı',
    noPerm: 'İzin yok',
    lastSentSec: (n: number) => `Gönderim: ${n} sn önce`,
    lastSentMin: (n: number) => `Gönderim: ${n} dk önce`,
  },
  warn: {
    permRevoked: 'Konum izni kapalı. Çağrı alamazsınız.',
    gpsOff: 'GPS kapalı. Açın, yoksa pasife düşersiniz.',
    gpsOn: 'KONUMU AÇ',
    probablyOffline: 'Uzun süredir bağlantı yok. Pasife düşmüş olabilirsiniz.',
    disconnected: (n: number) => `Bağlantı yok. ${n} sn içinde dönmezse pasife düşersiniz.`,
    autoReactivateHint: 'Bağlantı gelince otomatik olarak yeniden aktif olursunuz.',
    locationStale: 'Konum gönderilemiyor.',
    foregroundOnly: 'Uygulama kapalıyken çağrı alamazsınız.',
    foregroundOnlySub: '“Her zaman” konum izni verin.',
    fixPermission: 'İZNİ DÜZELT',
    poorAccuracy: 'Konum zayıf. Çağrılar gecikebilir.',
  },
  sync: {
    droppedTitle: 'Pasife alındınız',
    droppedGeneric: 'Çağrı almak için AKTİF OL’a basın.',
    droppedLong: '10 dakikadan uzun bağlantı yoktu. Çağrı almak için AKTİF OL’a basın.',
    droppedRepeated: 'Bağlantı tekrar tekrar koptu. Çağrı almak için AKTİF OL’a basın.',
    reactivatedTitle: 'Yeniden aktif oldunuz',
    reactivated: 'Bağlantı koptuğu için pasife düşmüştünüz. Bağlantı gelince otomatik olarak aktif oldunuz.',
    reactivateFailed: (reason: string, fix: string) =>
      `Bağlantı koptuğu için pasife düştünüz. ${reason} otomatik aktif olunamadı. ${fix}AKTİF OL’a basın.`,
    stillActiveTitle: 'Aktif durumdasınız',
    stillActive: 'Konum paylaşımı sürüyor.',
    forcedOfflineNoPerm: 'Konum izni olmadığı için pasife alındınız.',
  },
  /** Otomatik aktif olmanın başarısızlık nedenleri: [neden cümleciği, çözüm önerisi]. */
  reactivateReason: {
    gps: ['GPS kapalı olduğu için', 'GPS’i açıp '],
    perm: ['Konum izni kapalı olduğu için', 'İzni verip '],
    fix: ['Konum alınamadığı için', 'Açık alana çıkıp '],
    server: ['Sunucu yanıt vermediği için', ''],
  } as const,
  conn: { restored: 'Bağlantı geri geldi.' },
  gps: { offIos: 'Konum Servisleri kapalı. Ayarlar > Gizlilik > Konum Servisleri’nden açın.' },
  perm: {
    step: (n: number) => `ADIM ${n} / 2`,
    step1Title: 'Konum izni gerekli',
    step1Body: 'Aktif olduğunuzda yakınınızdaki durak çağrılarını alabilmeniz için konumunuz paylaşılır.',
    step1Points: ['Yalnızca aktifken paylaşılır', 'Pasifken konum paylaşılmaz', '“Tam konum”u açık bırakın'],
    step1Cta: 'İZİN VER',
    later: 'Şimdi değil',
    step2Title: 'Arka planda da çağrı alın',
    step2Body: 'Navigasyon açıkken veya ekran kilitliyken de aktif kalmanız için “Her zaman izin ver”i seçin.',
    step2Settings: 'AÇILAN AYARLARDA',
    step2Options: ['Her zaman izin ver', 'Yalnızca uygulama kullanılırken', 'Her seferinde sor'],
    step2Back: 'Ardından geri tuşuyla uygulamaya dönün.',
    step2Cta: 'DEVAM ET',
    coarse: '“Tam konum”u açın. Yaklaşık konumla çağrı alamazsınız.',
    deniedForever: 'Konum izni kapalı. Ayarlardan açın.',
    notifTitle: 'Bildirimler',
    notif: 'Aktifken bildirim çubuğunda durumunuzu görmek için bildirimlere izin verin.',
    notifCta: 'İZİN VER',
  },
  fgs: {
    title: 'DurakNet: Aktifsiniz',
    body: 'Çağrı alabilmeniz için konumunuz paylaşılıyor.',
  },
  notif: {
    dropped: 'Pasife alındınız. Çağrı almak için uygulamayı açın.',
    sessionEnded: 'Oturumunuz kapandı. Tekrar giriş yapın.',
  },
  session: {
    ended: 'Oturumunuz sona erdi. Tekrar giriş yapın.',
    suspended: 'Hesabınız askıya alındı. Durağınızla görüşün.',
    loggedOutElsewhere: 'Oturumunuz kapatıldı. Tekrar giriş yapın.',
  },
  account: {
    title: 'Hesap',
    fullName: 'Ad soyad',
    plate: 'Plaka',
    vehicle: 'Araç',
    phone: 'Telefon',
    locationPerm: 'Konum izni',
    notifPerm: 'Bildirim izni',
    battery: 'Pil tasarrufu',
    batteryValue: 'Kontrol edin',
    permAlways: 'Her zaman',
    permWhenInUse: 'Kullanırken',
    permNone: 'Kapalı',
    permAsk: 'Sorulmadı',
    notifOn: 'Açık',
    notifOff: 'Kapalı',
    version: (v: string, build: string) => `Uygulama sürümü ${v} (build ${build})`,
    sound: 'Çağrı sesi',
    soundOn: 'Açık',
    soundOff: 'Kapalı',
    soundHint: 'Kapalıyken yalnızca titreşim çalar.',
  },
  logout: {
    title: 'Çıkış yapılsın mı?',
    confirm: 'Bu hesap tüm cihazlarda kapanır.',
    confirmActive: 'Çıkış yaparsanız pasife alınırsınız ve çağrı alamazsınız. Bu hesap tüm cihazlarda kapanır.',
    cta: 'ÇIKIŞ YAP',
    cancel: 'VAZGEÇ',
    errNetwork: 'Sunucuya ulaşılamadı. Yine de çıkarsanız bu cihazdaki oturum silinir.',
    forceCta: 'YİNE DE ÇIK',
  },
  /** Faz 3: çağrı ve yolculuk ekranları (docs/design/faz3-dispatch.md Bölüm 5). */
  ride: {
    home: {
      openRequests: (n: number) => `${n} açık çağrı`,
      activeRide: (code: string) => `Aktif yolculuk · ${code}`,
      goToRide: 'YOLCULUĞA GİT',
      newBadge: 'YENİ',
    },
    banner: { newRequest: 'Yeni çağrı var.', see: 'GÖR' },
    req: {
      title: 'Gelen çağrı',
      openCount: (n: number) => `${n} açık çağrı`,
      accept: 'KABUL ET',
      decline: 'REDDET',
      accepting: 'Kabul ediliyor…',
      pickupLabel: 'ALIŞ NOKTASI',
      distance: (d: string) => `${d} uzakta`,
      distanceHint: 'alış noktasına',
      elapsed: (d: string) => `${d} önce`,
      justNow: 'az önce',
      new: 'YENİ',
      others: (n: number) => `DİĞER ÇAĞRILAR (${n})`,
      more: (n: number) => `+${n} çağrı daha`,
      taken: 'Çağrı başka şoföre gitti.',
      notAvailable: 'Şu an çağrı alamazsınız.',
      closedToast: 'Çağrı kapandı.',
      closedCount: (n: number) => `${n} çağrı kapandı.`,
      declined: 'Reddedildi.',
      undo: 'GERİ AL',
      declineFailed: 'Ret gönderilemedi. Çağrı yeniden görünüyor.',
      offline: 'Bağlantı yok.',
      offlineStrip: 'Bağlantı yok. Kabul için bağlantı gerekir.',
      waiting: 'Sonuç bekleniyor…',
      unknown: 'Sonuç alınamadı. Çağrı kapanmış olabilir.',
      errInternal: 'Kabul edilemedi. Tekrar deneyin.',
      loading: 'Çağrılar yükleniyor…',
      acceptA11y: (code: string, dist: string, addr: string) => `Kabul et. Çağrı ${code}, ${dist}, ${addr}`,
      declineA11y: (code: string) => `Reddet. Çağrı ${code}`,
      focusA11y: (i: number, n: number) => `Çağrı ${i}/${n}`,
    },
    detail: {
      matched: 'EŞLEŞTİNİZ',
      pickup: 'ALIŞ NOKTASI',
      dropoff: 'VARIŞ',
      note: 'NOT',
      stand: 'DURAK',
      navigate: 'NAVİGASYON',
      complete: 'MÜŞTERİ ALINDI / TAMAMLA',
      completing: 'Tamamlanıyor…',
      callStand: 'DURAĞI ARA',
      cancel: 'Çağrıyı iptal et',
      cancelling: 'İptal ediliyor…',
      navFailed: 'Harita açılamadı. Adresi elle girin.',
      offline: 'Bağlantı yok. Navigasyon kullanılabilir.',
      noLocation: 'Konumunuz paylaşılmıyor.',
      shareLocation: 'KONUM PAYLAŞ',
      sharingLocation: 'Konum paylaşılıyor',
      notSharing: 'Konum paylaşılmıyor',
      standPhoneLabel: 'Durak telefonu',
      changed: 'Yolculuk durumu değişti.',
      cancelledByYou: 'Çağrıyı iptal ettiniz. Yeniden aktifsiniz.',
      updating: 'Güncelleniyor…',
      navChoose: 'Harita uygulaması seçin',
      navDefault: 'Bunu varsayılan yap',
      navCancel: 'Vazgeç',
      completeErr: 'Tamamlanamadı. Tekrar deneyin.',
      cancelErr: 'İptal edilemedi. Tekrar deneyin.',
    },
    complete: { title: 'Yolculuk tamamlansın mı?', confirm: 'Müşteriyi aldınız mı? Yolculuk kapanacak.', cta: 'TAMAMLA', cancel: 'VAZGEÇ' },
    cancel: {
      title: 'Çağrıyı iptal et?',
      body: 'Çağrı yeniden aranacak. Bu çağrıyı bir daha almayacaksınız.',
      reasonLabel: 'Sebep (isteğe bağlı)',
      reasons: ['Araç arızası', 'Müşteriye ulaşamadım', 'Diğer'] as readonly string[],
      cta: 'ÇAĞRIYI İPTAL ET',
      keep: 'VAZGEÇ',
    },
    closed: {
      cancelledTitle: 'Çağrı iptal edildi',
      cancelled: 'Durak çağrıyı iptal etti. Navigasyona gerek yok.',
      cancelledReason: (r: string) => `Sebep: ${r}`,
      completedTitle: 'Yolculuk tamamlandı',
      completedByStand: 'Durak yolculuğu tamamladı.',
      completed: 'Teşekkürler. Yeniden aktifsiniz.',
      ok: 'TAMAM',
    },
    logout: {
      confirmBusy:
        'Aktif yolculuğunuz var. Çıkış yapsanız da yolculuk sürer; tekrar girince devam eder. Çıkarsanız konumunuz paylaşılmaz.',
    },
    session: { suspendedWithRide: 'Hesabınız askıya alındı. Yolculuk başka şoföre aktarıldı. Durağınızla görüşün.' },
    notif: {
      cancelled: 'Durak çağrıyı iptal etti.',
      suspended: 'Hesabınız askıya alındı. Yolculuk iptal edildi.',
    },
    a11y: { newRequest: (dist: string, addr: string) => `Yeni çağrı. ${dist}. ${addr}.`, newRequestMore: (n: number) => `Yeni çağrı daha. Toplam ${n}.` },
  },
} as const;
