// Yönetici raporları ve durak kaydı metinleri (Faz 6). Ana metinler texts.ts'tedir.

export const TA = {
  loginAdminTitle: 'Yönetici girişi',
  switchToAdmin: 'Yönetici girişi',
  switchToStand: 'Durak girişi',
  registerLink: 'Durak kaydı oluştur',
  admin: {
    title: 'Yönetici',
    reports: 'Raporlar',
    logout: 'ÇIKIŞ YAP',
  },
  reports: {
    title: 'Raporlar',
    from: 'Başlangıç',
    to: 'Bitiş',
    stand: 'Durak',
    allStands: 'Tüm duraklar',
    run: 'GETİR',
    loading: 'Yükleniyor…',
    csv: 'CSV İNDİR',
    tz: (tz: string) => `Günler ${tz} saat dilimindedir; gün, çağrının oluşturulma gününe göredir.`,
    note: 'Eşleşme süresi son aramadan eşleşmeye kadardır (şoför iptalinde sayaç yeniden başlar).',
    rangeInvalid: 'Geçerli bir tarih girin.',
    rangeOrder: 'Başlangıç, bitişten sonra olamaz.',
    rangeTooLong: (d: number) => `En fazla ${d} gün seçilebilir.`,
    cards: {
      total: 'Çağrı',
      matchRate: 'Eşleşme oranı',
      avg: 'Ort. süre',
      median: 'Medyan süre',
      p90: 'p90 süre',
      within: (s: number) => `${s} sn içinde eşleşen`,
      targetOk: 'Ortalama hedefin içinde',
      targetMiss: 'Ortalama hedefin üstünde',
    },
    table: {
      date: 'Tarih', total: 'Çağrı', matched: 'Eşleşen', completed: 'Tamamlanan', cancelled: 'İptal', open: 'Açık',
      matchRate: 'Eşleşme', avg: 'Ort.', median: 'Medyan', p90: 'p90', within: 'Hedef içi', totals: 'Toplam',
    },
    empty: 'Bu aralıkta çağrı yok.',
    errNetwork: 'İnternet bağlantısı yok.',
    errServer: 'Rapor alınamadı.',
    errForbidden: 'Bu rapor için yetkiniz yok.',
    errStands: 'Durak listesi alınamadı; tüm duraklar gösteriliyor.',
  },
  consistency: {
    title: 'Tutarlılık denetimi',
    check: 'DENETLE',
    checking: 'Denetleniyor…',
    ok: 'Tutarsızlık yok.',
    found: (n: number) => `${n} tutarsızlık bulundu.`,
    open: (n: number) => `Açık çağrı: ${n}`,
    checkedAt: 'Denetim zamanı',
    ride: 'Çağrı',
    kind: 'Sorun',
    pg: 'PG',
    redis: 'Redis',
    age: 'Yaş',
    kinds: {
      pg_open_redis_missing: 'PG açık, Redis kaydı yok',
      status_mismatch: 'Durum uyuşmazlığı',
      driver_mismatch: 'Şoför uyuşmazlığı',
      stale_created: 'Eski "created" çağrı',
      redis_open_pg_closed: 'Redis açık, PG kapalı',
    } as Record<string, string>,
    note: 'Salt okunur: onarım yapmaz; uzlaştırıcı kendi turunda düzeltir.',
  },
  register: {
    title: 'Durak kaydı',
    intro: 'Hesabınız yönetici onayından sonra açılır.',
    name: 'Durak adı',
    phone: 'Telefon',
    address: 'Adres (isteğe bağlı)',
    username: 'Kullanıcı adı',
    password: 'Şifre (en az 8 karakter)',
    lat: 'Enlem',
    lng: 'Boylam',
    useLocation: 'BU CİHAZIN KONUMUNU KULLAN',
    locating: 'Konum alınıyor…',
    locationFailed: 'Konum alınamadı. Enlem ve boylamı elle girin.',
    kvkkLabel: 'KVKK aydınlatma metnini okudum, kabul ediyorum.',
    kvkkRead: 'Metni oku',
    kvkkClose: 'KAPAT',
    kvkkRequired: 'Devam etmek için KVKK onayı gerekir.',
    submit: 'KAYIT OL',
    submitting: 'Gönderiliyor…',
    back: 'GİRİŞE DÖN',
    errName: 'Durak adını girin.',
    errPhone: 'Telefon numarasını kontrol edin (05XX XXX XX XX).',
    errUsername: 'Kullanıcı adı 3-60 karakter: harf, rakam, . _ -',
    errPassword: 'Şifre en az 8 karakter olmalı.',
    errLocation: 'Geçerli bir konum girin.',
    errConflict: 'Bu kullanıcı adı veya telefon zaten kayıtlı.',
  },
} as const;
